# Generated by Django 2.0 on 2018-03-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebase',
            name='file',
            field=models.FileField(upload_to='codebase/%Y%m%d65268', verbose_name='代码文件'),
        ),
    ]
