# Generated by Django 2.0 on 2018-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_auto_20180329_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebase',
            name='file',
            field=models.FileField(upload_to='codebase/%Y%m%d76367', verbose_name='代码文件'),
        ),
    ]
