# Generated by Django 2.0 on 2018-03-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_brand',
            field=models.CharField(choices=[('SystemX 3650M5', 'SystemX 3650M5'), ('ThinkServer RD630', 'ThinkServer RD630'), ('ThinkServer RD640', 'ThinkServer RD640'), ('ThinkServer RD650', 'ThinkServer RD650'), ('ThinkServer RD430', 'ThinkServer RD430')], default='SystemX 3650M5', max_length=64, verbose_name='资产品牌'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='资产编号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('服务器', '服务器'), ('交换机', '交换机')], default='服务器', max_length=64, verbose_name='资产类型'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetuid',
            field=models.CharField(default='1', max_length=64, unique=True, verbose_name='唯一号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='back_time',
            field=models.DateField(blank=True, null=True, verbose_name='归还时间'),
        ),
        migrations.AddField(
            model_name='asset',
            name='buy_time',
            field=models.DateField(default='1970-01-01', verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='asset',
            name='free_repair',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='保修期'),
        ),
        migrations.AddField(
            model_name='asset',
            name='give_time',
            field=models.DateField(blank=True, null=True, verbose_name='外借时间'),
        ),
        migrations.AddField(
            model_name='asset',
            name='person_incharge',
            field=models.CharField(choices=[('冷显慧', '冷显慧'), ('高绍阳', '高绍阳'), ('李福鑫', '李福鑫'), ('于晓辉', '于晓辉')], default='冷显慧', max_length=64, verbose_name='挂账人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='asset',
            name='remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='asset',
            name='role',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.CharField(choices=[('A1', 'A1'), ('D2', 'D2'), ('B201', 'B201'), ('B211', 'B211'), ('C1', 'C1')], max_length=64, null=True, verbose_name='机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('闲置', '闲置'), ('在用', '在用')], default='闲置', max_length=64, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.CharField(blank=True, choices=[('高瞻', '高瞻'), ('刘军', '刘军'), ('马亮亮', '马亮亮')], max_length=64, null=True, verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='asset',
            name='use_man',
            field=models.CharField(blank=True, choices=[('王正浩', '王正浩'), ('宋晓丽', '宋晓丽')], max_length=64, null=True, verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='assets/%Y%m%d70863', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='position',
            field=models.CharField(max_length=64, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(max_length=64, unique=True, verbose_name='序列号'),
        ),
    ]
