# Generated by Django 2.0 on 2018-03-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180329_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.data_centers', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='end_time',
            field=models.DateField(default='1970-01-01', verbose_name='到保时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='assets/%Y%m%d35123', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='network_ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='外网IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='product_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ship_time',
            field=models.DateField(default='1970-01-01', verbose_name='出厂时间'),
        ),
    ]
